spring:
  flyway:
    enabled: true
    locations: classpath:db/fixture, classpath:db/migration
  jpa:
    hibernate:
      ddl-auto: none
  modulith:
    events:
      jdbc-schema-initialization:
        enabled: true
  logging:
    level:
      org:
        flywaydb:
          core: DEBUG