spring:
  application:
    name: library
  datasource:
    url: jdbc:postgresql://localhost:5432/library_test
    username: dev
    password: pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  flyway:
    locations: classpath:db/fixture, classpath:db/migration
